version: '3.8'
 
services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always
 
  redis:
    image: redis:alpine
    container_name: redis_db
    ports:
      - "6379:6379"
    restart: always
